#! /bin/sh

trkfile_date_format="%Y-%m-%d"
trkdir_default="$HOME/.trk"
trkdir="$trkdir_default"
if [ ! -z "$TRK_DIR" ]; then
    trkdir="$TRK_DIR"
fi
trkfile="$trkdir/`date +$trkfile_date_format`.log"
trk_active_file="$trkdir/active_timer"

trk_workday_hours_default=8
trk_workday_hours=$trk_workday_hours_default
if [ ! -z "$TRK_WORKDAY_HOURS" ]; then
    trk_workday_hours="$TRK_WORKDAY_HOURS"
fi

tmpdir_default='/tmp'
tmpdir="$tmpdir_default"
if [ ! -z "$TMPDIR" ]; then
    # works in termux
    tmpdir="$TMPDIR"
fi

tag_valid_regex='[0-9A-Za-z_-]*'

print_env() {
echo "
export trkdir=$trkdir
export trk_active_file=$trk_active_file
export trkfile=$trkfile
export tmpdir=$tmpdir
"
}

help="
Usage:
    trk
        shows a 'today' report
    trk <entry_name>
        starts a timer tracking a named entry
    trk <time_spent> <entry_name>
        adds a new entry manually, with the specified time spent
        e.g.: '40m', '2h', '1h20m', etc., with 'h' and 'm' being
        [h]ours and [m]inutes
        (you can even use [d]ays and [s]econds, but why should you? :)
    trk t
        terminates the current timer
    trk r
    trk r today | month
        shows the monthly report
        or a report of the time range specified
    trk l
        lists the trk files
    trk e [trk_file]
        edit the trk file directly, defaulting to today trkfile
    trk y
        sync: commits eventual changes and do a pull/push of the trk dir
    trk g git_args
        runs git with git_args in the trk dir
    trk env
        prints exports of trk vars,
        eval-uating this output is useful for testing
    trk help | h
        shows help

Options:
    --help -h   Print this help

Notes:
    - trk default dir is [$trkdir_default]
    - to change default trk dir set TRK_DIR env var
    - trk default workday hours is 8
    - to change workday hours set TRK_WORKDAY_HOURS env var
    - to show debug infos set TRK_DEBUG env var to something
"

log() {
    local msg="$1"
    test -z "$TRK_DEBUG" || echo "$msg" >&2
}

ensure_trkdir_is_present() {
    test -d $trkdir || mkdir -p $trkdir
}

ensure_trkfile_is_present() {
    ensure_trkdir_is_present
    test -f "$trkfile" || touch "$trkfile"
}

edit_trkfile() {
    local filename="$1"
    local filepath="$trkdir/$file_name.log"

    if test -z "$filename"; then
        $EDITOR "$trkfile"
    elif test -r ; then
        $EDITOR "$filepath"
    else
        echo "no trk file named [$filename]" >&2
    fi
}

get_timestamp() {
    date '+%s'
}

is_there_a_pending_timer() {
    test -f $trk_active_file || return 2
    test ! -z "`cat $trk_active_file`"
}

stop_timer() {
    ensure_trkfile_is_present
    if is_there_a_pending_timer; then
        tag=`cat "$trk_active_file" | cut -d ' ' -f 1`
        start_ts=`cat "$trk_active_file" | cut -d ' ' -f 2`
        log "start timestamp: [$start_ts]"
        now=`get_timestamp`
        seconds_spent=`expr $now - $start_ts`
        humanized_time_spent=`get_friendly_time_from_seconds "$seconds_spent"`
        echo "$tag $humanized_time_spent" >> "$trkfile"
        echo -n '' > "$trk_active_file"
        compact_tags "$trkfile"
    else
        echo "no active timer to stop" 
    fi
}

start_timer() {
    local tag="$1"
    local now=`get_timestamp`

    is_there_a_pending_timer && stop_timer
    echo "$tag $now" >> "$trk_active_file"
}

get_seconds_from_friendly_time() {
    local time_spent="$1"

    days=`echo "$time_spent" | grep -o '[0-9]*d' | tr -d 'd'`
    hours=`echo "$time_spent" | grep -o '[0-9]*h' | tr -d 'h'`
    minutes=`echo "$time_spent" | grep -o '[0-9]*m' | tr -d 'm'`
    seconds=`echo "$time_spent" | grep -o '[0-9]*s' | tr -d 's'`
    
    workdays_in_hours=0
    test -z "$days" || \
       workdays_in_hours=`expr $trk_workday_hours \* $days`
    test -z "$hours" && hours=0
    dateline="`expr $workdays_in_hours + $hours` hours"
    test -z "$minutes" || dateline="$dateline $minutes minutes"
    test -z "$seconds" || dateline="$dateline $seconds seconds"

    log "dateline [$dateline]"

    now=`get_timestamp`
    future=`date -d "$dateline" '+%s'`
    secsspent=`expr $future - $now`
    log "time spent [$time_spent] is [$secsspent] seconds"
    echo -n "$secsspent"
}

get_friendly_time_from_seconds() {
    local seconds_spent="$1"
    
    log "converting [$seconds_spent] seconds to time spent"

    timeline="${seconds_spent}s"
    minutes_spent=`expr $seconds_spent / 60`
    hours_spent=`expr $minutes_spent / 60`
    days_spent=`expr $hours_spent / $trk_workday_hours`

    if [ $hours_spent -ge $trk_workday_hours ]; then
        days_in_hours=`expr $days_spent \* $trk_workday_hours`
        hours_remainder=`expr $hours_spent - $days_in_hours`
        hours_in_minutes=`expr $hours_spent \* 60`
        minutes_remainder=`expr $minutes_spent - $hours_in_minutes`
        timeline="${days_spent}d"
        test $hours_remainder -gt 0 && \
            timeline="${days_spent}d${hours_remainder}h"
        test $minutes_remainder -gt 0 && \
            timeline="${days_spent}d${minutes_remainder}m"
        test $hours_remainder -gt 0 && \
            test $minutes_remainder -gt 0 && \
        timeline="${days_spent}d${hours_remainder}h${minutes_remainder}m"

    elif [ $minutes_spent -ge 60 ]; then
        hours_in_minutes=`expr $hours_spent \* 60`
        minutes_remainder=`expr $minutes_spent - $hours_in_minutes`
        timeline="${hours_spent}h"
        test $minutes_remainder -gt 0 && \
            timeline="${hours_spent}h${minutes_remainder}m"

    elif [ $seconds_spent -ge 60 ]; then
        timeline="${minutes_spent}m"
    fi

    log "[$seconds_spent] seconds are [$timeline] time spent"
    echo "$timeline"
}

add_entry() {
    local tag="$1"
    local time_spent="$2"

    if [ -z "$tag" ]; then
        echo "missing tag"
        exit 1
    fi
    if [ -z "$time_spent" ]; then
        echo "missing time spent"
        exit 1
    fi

    entry="$tag $time_spent"
    log "adding entry [$entry]"
    echo "$entry" >> "$trkfile"
    compact_tags "$trkfile"
}

get_unique_tag_list() {
    local trkfile_to_compact="$1"
    test -z "$trkfile_to_compact" && trkfile_to_compact="$trkfile"
    cat $trkfile_to_compact | grep -o "^$tag_valid_regex" | sort | uniq
}

compact_tags() {
    local trkfile_to_compact="$1"
    test -z "$trkfile_to_compact" && trkfile_to_compact="$trkfile"
    local temp_trk_file="$tmpdir/`basename $trkfile_to_compact`-compacting"

    test -f $temp_trk_file && rm -f $temp_trk_file
    unique_tag_list=`get_unique_tag_list "$trkfile_to_compact"`
    for tag in $unique_tag_list; do
        log "processing tag [$tag]"
        tag_total_seconds_spent=0
        while read entry; do
            echo -n "$entry" | \
                grep "^$tag " >/dev/null || \
                continue
            log "found entry [$entry]"
            time_spent=`echo "$entry" | cut -d ' ' -f 2`
            log "time_spent [$time_spent]"
            seconds_spent=`get_seconds_from_friendly_time $time_spent`
            tag_total_seconds_spent=`expr $tag_total_seconds_spent + $seconds_spent`
        done < "$trkfile_to_compact"
        humanized_time_spent=`get_friendly_time_from_seconds "$tag_total_seconds_spent"`
        echo "$tag $humanized_time_spent" >> "$temp_trk_file"
    done
    mv -f "$temp_trk_file" "$trkfile_to_compact"
    test -f "$temp_trk_file" && rm -f "$temp_trk_file"
}

get_active_entry() {
    if ! is_there_a_pending_timer; then
        return
    fi
    local now=`get_timestamp`
    local tag=`cat "$trk_active_file" | cut -d ' ' -f 1`
    local entry_start_time=`cat "$trk_active_file" | cut -d ' ' -f 2`

    log "entry_start_time: [$entry_start_time]"
    log "tag: [$tag]"

    local seconds_spent=`expr $now - $entry_start_time`
    local friendly_time=`get_friendly_time_from_seconds "$seconds_spent"`

    echo -n "$tag $friendly_time"
}

show_report() {
    local from="$1"
    local to="$2"
    local reportfile="$tmpdir/trkreportfile"

    echo
    if [ "$from" = "today" ]; then
        echo 'today report:'
        ensure_trkfile_is_present
        _show_report "$trkfile"
    elif [ "$from" = "month" ]; then
        echo 'monthly report:'
        pattern="`date '+%Y-%m-*'`.log"
        cat $trkdir/$pattern >$reportfile
        compact_tags "$reportfile"
        _show_report "$reportfile"
        test -f "$reportfile" && rm -f "$reportfile"
    fi

    active_entry=`get_active_entry`
    if test ! -z "$active_entry"; then
        echo
        print_active_entry_info $active_entry
    fi
}

_show_report() {
    local trkfile_to_report="$1"

    total_seconds_spent=0
    echo
    while read entry; do
        log "found entry [$entry]"
        tag=`echo "$entry" | cut -d ' ' -f 1`
        time_spent=`echo "$entry" | cut -d ' ' -f 2`
        log "time_spent [$time_spent]"
        seconds_spent=`get_seconds_from_friendly_time $time_spent`
        total_seconds_spent=`expr $total_seconds_spent + $seconds_spent`
        print_entry_info "$tag" "$time_spent"
    done < "$trkfile_to_report"
    echo
    tot_friendly_time="`get_friendly_time_from_seconds "$total_seconds_spent"`"
    echo "[$tot_friendly_time] spent in total"
}

print_entry_info() {
    local tag="$1"
    local time="$2"
    echo "$time spent on $tag"
}

print_active_entry_info() {
    local tag="$1"
    local time="$2"
    echo "$time spent working on $tag (active entry)"
}

ensure_trkdir_is_present

command="$1"

if [ -z "$command" ]; then
    show_report 'today'
    echo
    echo "run [`basename $0` h] for help"

elif [ "$command" = "t" ]; then
    stop_timer
    show_report 'today'

elif [ "$command" = "l" ]; then
    cd $trkdir
    ls -1 *.log | sed 's/\.log//'
    cd - >/dev/null

elif [ "$command" = "e" ]; then
    file_name="$2"
    edit_trkfile $file_name

elif [ "$command" = "r" ]; then
    from="$2"
    to="$3"
    test -z "$from" && from="month"
    show_report $from $to

elif [ "$command" = "y" ]; then
    cd $trkdir
    git status | grep 'nothing to commit' &>/dev/null
    test $? = 1 && git add -A && git commit -am 'trk autosync'
    git pull && git push

elif [ "$command" = "g" ]; then
    shift 1
    cd $trkdir
    git $@

elif [ "$command" = "env" ]; then
    print_env

elif [ "$command" = "--help" ] \
    || [ "$command" = "-h" ] \
    || [ "$command" = "help" ] \
    || [ "$command" = "h" ] ; then
    echo "$help"
else
    tag="$command"
    if test -z "$2"; then
        start_timer "$tag"
    else
        time_spent="$command"
        tag="$2"
        add_entry "$tag" "$time_spent"
    fi
fi

