#! /bin/bash

trkfile_date_format="%Y-%m-%d"
trkdir_default="$HOME/.trk"
trkdir="$trkdir_default"
if [ ! -z "$TRK_DIR" ]; then
    trkdir="$TRK_DIR"
fi
trkfile="$trkdir/`date +$trkfile_date_format`.log"
trk_active_file="$trkdir/active_timer"

trk_workday_hours_default=8
trk_workday_hours=$trk_workday_hours_default
if [ ! -z "$TRK_WORKDAY_HOURS" ]; then
    trk_workday_hours="$TRK_WORKDAY_HOURS"
fi

tmpdir_default='/tmp'
tmpdir="$tmpdir_default"
if [ ! -z "$TMPDIR" ]; then
    # works in termux
    tmpdir="$TMPDIR"
fi

tag_valid_regex='[0-9A-Za-z_-]*'

print_env() {
echo "
export trkdir=$trkdir
export trk_active_file=$trk_active_file
export trkfile=$trkfile
export tmpdir=$tmpdir
"
}

read -r -d '' help <<EOF
Usage:
    trk
        shows a "today" report and the current timer, if active
    trk <entry_name>
        starts timer tracking a named entry
    trk <entry_name> <time_spent>
        adds a new entry manually, with the specified time spent
        e.g.: "1h", "1h20m", "2d", etc.
    trk t
        terminates the current timer
    trk r [from] [to]
        shows a report of the time range specified
        format of the time range is $trkfile_date_format
    trk l
        lists the trk files
    trk e [trk_file]
        edit the trk file directly, only for the brave
    trk clean
        backup the current trk file and starts anew
    trk y
        sync: commits eventual changes and do a pull/push of the trk dir
    trk g git_args
        runs git with git_args in the trk dir
    trk env
        prints exports of trk vars,
        eval-uating this output is useful for testing
    trk help | h
        shows help

Options:
    --help -h   Print this help

Notes:
    - trk default dir is [$trkdir_default]
    - to change default trk dir set TRK_DIR env var
    - trk default workday hours is 8
    - to change workday hours set TRK_WORKDAY_HOURS env var
    - to show debug infos set TRK_DEBUG env var to something
EOF

log() {
    local msg="$1"
    test -z "$TRK_DEBUG" || echo "$msg" >&2
}

ensure_trkdir_is_present() {
    test -d $trkdir || mkdir -p $trkdir
}

ensure_trkfile_is_present() {
    ensure_trkdir_is_present
    test -f "$trkfile" || touch "$trkfile"
}

edit_trkfile() {
    local filename="$1"
    local filepath="$trkdir/$file_name.log"

    if test -z "$filename"; then
        $EDITOR "$trkfile"
    elif test -r ; then
        $EDITOR "$filepath"
    else
        echo "no trk file named [$filename]" >&2
    fi
}

get_timestamp() {
    date '+%s'
}

is_there_a_pending_timer() {
    test -f $trk_active_file || return 2
    test ! -z "`cat $trk_active_file`"
}

stop_timer() {
    ensure_trkfile_is_present
    if is_there_a_pending_timer; then
        tag=`cat "$trk_active_file" | cut -d ' ' -f 1`
        start_ts=`cat "$trk_active_file" | cut -d ' ' -f 2`
        log "start timestamp: [$start_ts]"
        now=`get_timestamp`
        seconds_spent=`expr $now - $start_ts`
        humanized_time_spent=`get_humanized_interval "$seconds_spent"`
        echo "$tag $humanized_time_spent" >> "$trkfile"
        echo -n '' > "$trk_active_file"
    else
        echo "no active timer to stop" 
    fi
}

start_timer() {
    local tag="$1"
    local now=`get_timestamp`

    ensure_trkfile_is_present
    is_there_a_pending_timer && stop_timer
    echo "$tag $now" >> "$trk_active_file"
}

show_filtered_log() {
    local filter="$1"
    grep -A1 "$filter" "$trkfile"
}

show_today_log() {
    test -r "$trkfile" && cat "$trkfile"
}

show_full_log() {
    if [ 0 -eq `ls "$trkdir" | wc -l` ]; then
        return
    fi
    cat $trkdir/*.log
}

show_today_tags() {
    show_today_log | \
        grep '^[a-zA-Z0-9_\-\.]*' | \
        sort | uniq
}

show_tags() {
    show_full_log | \
        grep '^[a-zA-Z0-9_\-\.]*' | \
        sort | uniq
}

is_the_current_active_timer_entry() {
    local entry_start_timestamp="$1"
    test `show_today_log | grep -A1 "$entry_start_timestamp" | wc -l` -eq 1
    return $?
}

get_seconds_from_time_spent() {
    local time_spent="$1"

    days=`echo "$time_spent" | grep -o '[0-9]*d' | tr -d 'd'`
    hours=`echo "$time_spent" | grep -o '[0-9]*h' | tr -d 'h'`
    minutes=`echo "$time_spent" | grep -o '[0-9]*m' | tr -d 'm'`
    seconds=`echo "$time_spent" | grep -o '[0-9]*s' | tr -d 's'`
    
    workdays_in_hours=0
    test -z "$days" || \
       workdays_in_hours=`expr $trk_workday_hours \* $days`
    test -z "$hours" && hours=0
    dateline="`expr $workdays_in_hours + $hours` hours"
    test -z "$minutes" || dateline="$dateline $minutes minutes"
    test -z "$seconds" || dateline="$dateline $seconds seconds"

    log "dateline [$dateline]"

    now=`get_timestamp`
    future=`date -d "$dateline" '+%s'`
    secsspent=`expr $future - $now`
    log "time spent [$time_spent] is [$secsspent] seconds"
    echo -n "$secsspent"
}

get_humanized_interval() {
    local seconds_spent="$1"
    
    log "converting [$seconds_spent] seconds to time spent"

    timeline="${seconds_spent}s"
    minutes_spent=`expr $seconds_spent / 60`
    hours_spent=`expr $minutes_spent / 60`
    days_spent=`expr $hours_spent / $trk_workday_hours`

    if [ $hours_spent -ge $trk_workday_hours ]; then
        days_in_hours=`expr $days_spent \* $trk_workday_hours`
        hours_remainder=`expr $hours_spent - $days_in_hours`
        hours_in_minutes=`expr $hours_spent \* 60`
        minutes_remainder=`expr $minutes_spent - $hours_in_minutes`
        timeline="${days_spent}d"
        test $hours_remainder -gt 0 && \
            timeline="${days_spent}d${hours_remainder}h"
        test $minutes_remainder -gt 0 && \
            timeline="${days_spent}d${minutes_remainder}m"
        test $hours_remainder -gt 0 && \
            test $minutes_remainder -gt 0 && \
        timeline="${days_spent}d${hours_remainder}h${minutes_remainder}m"

    elif [ $minutes_spent -ge 60 ]; then
        hours_in_minutes=`expr $hours_spent \* 60`
        minutes_remainder=`expr $minutes_spent - $hours_in_minutes`
        timeline="${hours_spent}h"
        test $minutes_remainder -gt 0 && \
            timeline="${hours_spent}h${minutes_remainder}m"

    elif [ $seconds_spent -ge 60 ]; then
        timeline="${minutes_spent}m"
    fi

    log "[$seconds_spent] seconds are [$timeline] time spent"
    echo "$timeline"
}

add_entry() {
    local tag="$1"
    local time_spent="$2"

    if [ -z "$tag" ]; then
        echo "missing tag"
        exit 1
    fi
    if [ -z "$time_spent" ]; then
        echo "missing time spent"
        exit 1
    fi

    entry="$tag $time_spent"
    log "adding entry [$entry]"
    echo "$entry" >> "$trkfile"
    compact_tags "$trkfile"
}

get_last_trk_line() {
    test -r $trkfile && tail -n1 "$trkfile"
}

print_tag_info() {
    local tag="$1"
    local seconds_spent="$2"
    echo "spent `get_humanized_interval "$seconds_spent"` on $tag"
}

show_today_report() {
    local now=`get_timestamp`

    echo "report (with active timer included):"
    echo
    total_seconds_spent=0
    for tag in `show_today_tags`; do
        tag_seconds_spent=0
        for entry_start_time in `get_today_entry_start_timestamps "$tag"`; do
            seconds_spent=`get_seconds_spent $entry_start_time $now`
            tag_seconds_spent=`expr $tag_seconds_spent + $seconds_spent`
        done
        print_tag_info "$tag" "$tag_seconds_spent"
        total_seconds_spent=`expr $total_seconds_spent + $tag_seconds_spent`
    done
    echo
    echo "total time spent: [`get_humanized_interval "$total_seconds_spent"`]"
}

get_unique_tag_list() {
    local trkfile_to_compact="$1"
    test -z "$trkfile_to_compact" && trkfile_to_compact="$trkfile"
    cat $trkfile_to_compact | grep -o "^$tag_valid_regex" | sort | uniq
}

compact_tags() {
    local trkfile_to_compact="$1"
    test -z "$trkfile_to_compact" && trkfile_to_compact="$trkfile"
    local temp_trk_file="$tmpdir/`basename $trkfile_to_compact`-compacting"

    test -f $temp_trk_file && rm -f $temp_trk_file
    unique_tag_list=`get_unique_tag_list "$trkfile_to_compact"`
    for tag in $unique_tag_list; do
        log "processing tag [$tag]"
        tag_total_seconds_spent=0
        while read entry; do
            echo -n "$entry" | \
                grep "^$tag " >/dev/null || \
                continue
            log "found entry [$entry]"
            time_spent=`echo "$entry" | cut -d ' ' -f 2`
            log "time_spent [$time_spent]"
            seconds_spent=`get_seconds_from_time_spent $time_spent`
            tag_total_seconds_spent=`expr $tag_total_seconds_spent + $seconds_spent`
        done < "$trkfile_to_compact"
        humanized_time_spent=`get_humanized_interval "$tag_total_seconds_spent"`
        echo "$tag $humanized_time_spent" >> "$temp_trk_file"
    done
    mv -f "$temp_trk_file" "$trkfile_to_compact"
    test -f "$temp_trk_file" && rm -f "$temp_trk_file"
}

show_current_entry() {
    if ! is_there_a_pending_timer; then
        echo 'no active timer'
        return
    fi
    local now=`get_timestamp`
    local current_entry_line=`get_last_trk_line`
    local entry_start_time=`extract_timestamp_from_start_entry "$current_entry_line"`
    local tag=`extract_tag_from_start_entry "$current_entry_line"`

    log "entry_start_time: [$entry_start_time]"
    log "tag: [$tag]"

    local seconds_spent=`get_seconds_spent "$entry_start_time" "$now"`
    local humanized_time_spent=`get_humanized_interval "$seconds_spent"`

    echo "active timer:"
    echo "$humanized_time_spent spent on $tag"
}

show_report() {
    local from="$1"
    local to="$2"
    local now=`get_timestamp`

    echo "report from [$from] to [$to]:"
    echo
    total_seconds_spent=0
    for tag in `show_tags`; do
        tag_seconds_spent=0
        for entry_start_time in `get_entry_start_timestamps "$tag"`; do
            seconds_spent=`get_seconds_spent $entry_start_time $now`
            tag_seconds_spent=`expr $tag_seconds_spent + $seconds_spent`
        done
        print_tag_info "$tag" "$tag_seconds_spent"
        total_seconds_spent=`expr $total_seconds_spent + $tag_seconds_spent`
    done
    echo
    echo "total time spent: [`get_humanized_interval "$total_seconds_spent"`]"
}

clean_trk() {
    mv "$trkfile" "$trkfile.bak"
}

ensure_trkdir_is_present

command="$1"

if [ -z "$command" ]; then
    show_today_report
    echo
    show_current_entry
    echo
    echo "run [`basename $0` h] for help"

elif [ "$command" = "s" ] \
    || [ "$command" = "t" ]; then
    stop_timer

elif [ "$command" = "l" ]; then
    cd $trkdir
    ls -1 *.log | sed 's/\.log//'
    cd - >/dev/null

elif [ "$command" = "e" ]; then
    file_name="$2"
    edit_trkfile $file_name

elif [ "$command" = "r" ]; then
    from="$2"
    to="$3"
    show_report $from $to

elif [ "$command" = "y" ]; then
    cd $trkdir
    git status | grep 'nothing to commit' &>/dev/null
    test $? = 1 && git add -A && git commit -am 'trk autosync'
    git pull && git push

elif [ "$command" = "g" ]; then
    shift 1
    cd $trkdir
    git $@

elif [ "$command" = "clean" ]; then
    clean_trk

elif [ "$command" = "env" ]; then
    print_env

elif [ "$command" = "--help" ] \
    || [ "$command" = "-h" ] \
    || [ "$command" = "help" ] \
    || [ "$command" = "h" ] ; then
    echo "$help"
else
    tag="$command"
    time_spent="$2"
    if test -z "$time_spent"; then
        start_timer "$tag"
    else
        add_entry "$tag" "$time_spent"
    fi
fi

