#! /bin/sh
version="0.1.0"
trkfile="${TRK_FILE:-$HOME/.trkfile}"
trk_workday_hours="${TRK_WORKDAY_HOURS:-8}"
editor="${EDITOR:-vi}"
tmpdir="${TMPDIR:-/tmp}"
logfile="$tmpdir/trk-harvest.log"
harvest_trk_tag="#hid"

# one-character separator
task_assignment_separator='~'

usage() {
    s="$(basename $0)"
    printf "Usage [v$version]:
    $s l [grep_pattern | date_arg]
        list time entries from harvest, filtering records with grep_pattern or a date_arg if passed.
        date_arg is any valid value the 'date' command can take, e.g. '-', 'today', 'yesterday', etc.
        hours spent must be a number and can be decimal: 1, 4.25, 0.5, etc.

    $s t [column_opts]
    $s tt [column_opts]
        get harvest tasks assigned to your user
        the task list is cached in your tmpdir, use 'tt' to force-refresh it
        the output is produced by the 'column' linux command, you can pass options to it

    $s a <date_arg> <hours> <task_id> <notes>
        adds a new entry to the harvest.

    $s d <entry_id>
        deletes a time entry by id from harvest.

    $s p [grep_pattern | date_arg]
        output the changes that will be made on harvest to align with trk entries
        for the specified pattern/date_arg

    $s s [grep_pattern | date_arg]
        one way sync from trk to harvest to align harvest with trk entries
        for the specified pattern/date_arg

    $s h
        shows extended help
"
}
helpmsg() {
    usage; echo
    printf "filtering:
    the l[ist], a[dd], p[lan] and s[ync] commands optionally take a grep pattern or a date arg as input.
    the grep pattern is obviously grep-compatible a regex.
    The date arg is a value that is a valid 'date' command 'DATE STRING': something like yesterday, 7 days ago, etc. 
    $s tries to be smart, e.g.: if the date arg contains 'month' or 'week', then it adjust the resulting filter to grep the entire month/week.

task mapping:
    WIP documentation

env vars:
    - TRK_HARVEST_USER_ID: set it to your harvest user id [cur: ${TRK_HARVEST_USER_ID:-unset}]
    - TRK_HARVEST_ACCOUNT_ID: set it to your harvest account id [cur: ${TRK_HARVEST_ACCOUNT_ID:-unset}]
    - TRK_HARVEST_ACCESS_TOKEN: set it to your harvest access token [cur: ${TRK_HARVEST_ACCESS_TOKEN:-unset}]
"
}
_now() { date '+%Y-%m-%dT%H:%M:%S'; }
_err() { printf "%s: error: %s\n" "$(basename "$0")" "$1" >&2; exit 1; }
_warn() { printf "%s: warn: %s\n" "$(basename "$0")" "$1" >&2; }
_info() { printf "%s: %s\n" "$(basename "$0")" "$1" >&2; }
_dbg() { [ "$TRK_DEBUG" ] && printf "%s %s: debug: %s\n" "$(_now)" "$(basename "$0")" "$1" >&2; return 0; }
_mktemp() { tmpdir=/dev/shm; [ -w /dev/shm ] || tmpdir=${TMPDIR:-/tmp}; echo "mkstemp($tmpdir/XXXXXXXX)" | m4; }
_today() { date '+%Y-%m-%d'; }
_validate_date() { date -d "$(printf "$1")" >/dev/null 2>&1;}
_validate_hours() { printf "$1" | grep -qE '^[+-]?[0-9]+(\.[0-9]+)?$';}
_calculate_grep_pattern() { trk run _calculate_grep_pattern "$@"; }
_get_time_entries() {
    curl -s --fail "https://api.harvestapp.com/v2/time_entries?user_id=$TRK_HARVEST_USER_ID" \
      -H "Authorization: Bearer $TRK_HARVEST_ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $TRK_HARVEST_ACCOUNT_ID" |
       jq -r '.time_entries.[] | "\(.spent_date) \(.hours) eid:\(.id) tid:\(.task.id) \(.notes)"'
}
_list_time_entries() {
    [ -z "$1" ] && [ -t 0 ] && _get_time_entries | grep -v '^#' && return 0
    _dbg "list args input: $*"; set -- "$(_calculate_grep_pattern "$*")"; _dbg "computed input: $*"
    [ -n "$1" ] && [ -t 0 ] && _get_time_entries | grep -v '^#' | grep "$*" && return 0
}
list_time_entries() {
    entries="$(_list_time_entries "$@")"
    tot=0
    for e in $(echo "$entries" | cut -d' ' -f2); do [ -z "$e" ] && continue
        tot=$(echo "$tot + $e" | bc -l); done
    echo "$entries"; echo
    echo "tot: $(trk run _get_friendly_time_from_hours $tot)"
}
list_and_cache_task_assignments() {
    force_refresh="$1"
    task_cache_file="$tmpdir/trk-harvest-task-cache.json"
    project_cache_file="$tmpdir/trk-harvest-project-cache.json"
    assignment_cache_file="$tmpdir/trk-harvest-assignment-cache.txt"

    ( [ -n "$force_refresh" ] || [ ! -r "$project_cache_file" ] ) && 
    curl -s --fail "https://api.harvestapp.com/v2/projects" \
      -H "Authorization: Bearer $TRK_HARVEST_ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $TRK_HARVEST_ACCOUNT_ID" > "$project_cache_file"
      cat "$project_cache_file" |

    ( [ -n "$force_refresh" ] || [ ! -r "$task_cache_file" ] ) && 
    curl -s --fail "https://api.harvestapp.com/v2/task_assignments" \
      -H "Authorization: Bearer $TRK_HARVEST_ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $TRK_HARVEST_ACCOUNT_ID" > "$task_cache_file"

    ( [ -n "$force_refresh" ] || [ ! -r "$assignment_cache_file" ] ) && {
    printf '' > "$assignment_cache_file"
    cat "$task_cache_file" |
      jq -r '.task_assignments[] | "tid:\(.task.id)'$task_assignment_separator'pid:\(.project.id)'$task_assignment_separator'\(.project.name)'$task_assignment_separator'\(.task.name)"' |
      while read c; do
          project_id="$(echo "$c" | grep -o 'pid:[0-9]\{1,\}' | sed 's/pid://')"
          client="$(cat "$project_cache_file" | jq -r '.projects[] | select( .id == '$project_id') | "cid:\(.client.id)'$task_assignment_separator'\(.client.name)"')"
          field_task_id="$(echo "$c" | cut -d"$task_assignment_separator" -f1)"
          field_project_id="$(echo "$c" | cut -d"$task_assignment_separator" -f2)"
          field_project_name="$(echo "$c" | cut -d"$task_assignment_separator" -f3)"
          field_task_name="$(echo "$c" | cut -d"$task_assignment_separator" -f4)"
          field_client_id="$(echo "$client" | cut -d"$task_assignment_separator" -f1)"
          field_client_name="$(echo "$client" | cut -d"$task_assignment_separator" -f2)"
          s="$task_assignment_separator"
          printf "%s$s%s$s%s$s%s$s%s$s%s\n" \
            "$field_client_id" \
            "$field_project_id" \
            "$field_task_id" \
            "$field_client_name" \
            "$field_project_name" \
            "$field_task_name" \
            >> "$assignment_cache_file"
      done
      cat "$assignment_cache_file" |
        sort -t"$task_assignment_separator" -k4 -k5 -k6 \
        > "$assignment_cache_file.sorted"
      mv "$assignment_cache_file.sorted" "$assignment_cache_file"
    }
    cat "$assignment_cache_file"
}
print_task_assignments() { list_and_cache_task_assignments | sed 's/'$task_assignment_separator'/ | /g'; }
print_task_assignments_refresh() { list_and_cache_task_assignments "refresh" | sed 's/'$task_assignment_separator'/ | /g'; }
_add_time_entry() {
    day="$1"
    hours="$2"
    taskid="$3"
    notes="$4"
    _dbg "adding entry: [$*]"
    projectid=$(list_and_cache_task_assignments | grep "^tid:$taskid" | cut -d"$task_assignment_separator" -f2 | sed 's/pid://' | tr -d ' ')
    _dbg "found project id: [$projectid]"
    curl -s --fail -o /dev/null "https://api.harvestapp.com/v2/time_entries" \
      -H "Authorization: Bearer $TRK_HARVEST_ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $TRK_HARVEST_ACCOUNT_ID" \
      -X POST \
      -H "Content-Type: application/json" \
      -d '{"user_id":'"$TRK_HARVEST_USER_ID"',"project_id":'"$projectid"',"task_id":'"$taskid"',"spent_date":"'"$day"'","hours":'"$hours"',"notes":"'"$notes"'"}' || return 1
}
add_time_entry() {
    day="$1"
    hours="$2"
    taskid="$3"
    [ -z "$3" ] && usage && exit 1
    shift; shift; shift
    notes="$*"
    ! _validate_date "$day" &&
        _err "date [$day] is not a valid date" && exit 1
    day="$(date -d "$day" '+%Y-%m-%d')"
    ! _validate_hours "$hours" &&
        _err "hours spent [$hours] is not a valid number" && exit 1
    _add_time_entry "$day" "$hours" "$taskid" "$notes" ||
        _err "error adding entry: $day $hours taskid:$taskid $notes"
    _info "entry added: $day $hours taskid:$taskid $notes"
}
delete_time_entry() {
    entryid="$1"
    curl --fail -s -o /dev/null "https://api.harvestapp.com/v2/time_entries/$entryid" \
      -H "Authorization: Bearer $TRK_HARVEST_ACCESS_TOKEN" \
      -H "Harvest-Account-Id: $TRK_HARVEST_ACCOUNT_ID" \
      -X DELETE ||
        _err "error deleting entry: $entryid"
    _info "entry deleted:  $entryid"
}
_compare_trk_and_harvest_entry() {
    t="$1"
    h="$2"

    tday="$(echo "$t" | cut -d' ' -f1)"
    thours="$(echo "$t" | cut -d' ' -f2)"
    ttaskid="$(echo "$t" | grep -o "$harvest_trk_tag:[0-9]*" | sed "s/$harvest_trk_tag://" | tr -d ' ')"
    tnotes="$(echo "$t" | cut -d' ' -f3- | sed 's/#.[^ ]*//g' | sed 's/^ *//' | sed 's/ *$//')"

    hday="$(echo "$h" | cut -d' ' -f1)"
    hhours="$(echo "$h" | cut -d' ' -f2 | sed 's/\.0$//')"
    htaskid="$(echo "$h" | grep -o 'tid:[0-9]*' | sed 's/tid://' | tr -d ' ')"
    hnotes="$(echo "$h" | cut -d' ' -f5-)"

    _dbg "comparing: [$tday] = [$hday] ;[$thours] = [$hhours] ;[$ttaskid] = [$htaskid] ;[$tnotes] = [$hnotes] ;"

    [ "$tday" = "$hday" ] &&
    [ "$thours" = "$hhours" ] &&
    [ "$ttaskid" = "$htaskid" ] &&
    [ "$tnotes" = "$hnotes" ] &&
    return 0
    return 1
}
plan() {
    _dbg "getting trk entries"
    trk_entries="$(trk l "$@" | grep "$harvest_trk_tag:" )"
    _dbg "getting harvest entries"
    harvest_entries="$(_list_time_entries "$@")"

    _dbg "checking for duplicated trk entries"
    duplicates="$(echo "$trk_entries" | uniq -d)"
    [ -n "$duplicates" ] &&
        _warn "there are some duplicated trk entries, the sync will not work as expected: $duplicates"

    _dbg "building plan"
    plan_file="$(_mktemp)"; trap "rm -f $plan_file" EXIT
    while read t; do
        found=""
        _dbg "searching match for trk entry [$t]"
        while read h; do
            [ -z "$(printf "$h" | tr -d ' ')" ] && continue
            _compare_trk_and_harvest_entry "$t" "$h" &&
            _dbg "match found [$h]" &&
            found='y' && break
        done <<EOFH
$harvest_entries
EOFH
        [ -z "$found" ] && echo "+ $t" >>"$plan_file"
        [ -n "$found" ] && echo "✓ $t" >>"$plan_file"
    done <<EOFT &
$trk_entries
EOFT
    while read h; do
        [ -z "$(printf "$h" | tr -d ' ')" ] && continue
        found=""
        _dbg "searching match for hrv entry [$h]"
        while read t; do
            _compare_trk_and_harvest_entry "$t" "$h" &&
            _dbg "match found [$t]" &&
            found='y' && break
        done <<EOFT
$trk_entries
EOFT
        [ -z "$found" ] && echo "- $h" >>"$plan_file"
    done <<EOFH &
$harvest_entries
EOFH
    wait
    _info "plan:"
    cat "$plan_file" | grep '^✓' | sort -k2; echo
    cat "$plan_file" | grep -v '^✓' | sort -k2
}
sync() {
    plan="$(plan "$@" | grep -v '^✓ ')"
    [ -z "$plan" ] && _info "nothing to sync" && return 0
    echo "$plan" ; echo
    _info "syncing harvest..."
    while read p; do
        if echo "$p" | grep '^+' >/dev/null; then
            t="$(echo "$p" | sed 's/^+ //')"
            day="$(echo "$t" | cut -d' ' -f1)"
            hours="$(echo "$t" | cut -d' ' -f2)"
            taskid="$(echo "$t" | grep -o "$harvest_trk_tag:[0-9]*" | sed "s/$harvest_trk_tag://" | tr -d ' ')"
            notes="$(echo "$t" | cut -d' ' -f3- | sed 's/#.[^ ]*//g' | sed 's/^ *//' | sed 's/ *$//')"
            add_time_entry "$day" "$hours" "$taskid" "$notes"
        fi
        if echo "$p" | grep '^-' >/dev/null; then
            entryid="$(echo "$p" | grep -o 'eid:[0-9]*' | sed 's/eid://' | tr -d ' ')"
            delete_time_entry "$entryid"
        fi
    done <<EOF &
$plan
EOF
    wait
}

main() {
    cmd="$1"; shift
    case $cmd in
        t) print_task_assignments "$@";;
        tt) print_task_assignments_refresh "$@";;
        l) list_time_entries "$@";;
        a) add_time_entry "$@";;
        d) delete_time_entry "$@";;
        p) plan "$@";;
        s) sync "$@";;
        h) helpmsg && exit 0;;
        run) "$@";;
    esac
}
scriptname=$(basename $0)
[ "$1" ] || { usage; exit 0; } && main "$@"
